  vscode:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    volumes:
      - "./:/data"
      - "./data/vscode-config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - PASSWORD=CHANGEME
      - DEFAULT_WORKSPACE=/data
      - PROXY_DOMAIN='my.domain.com'