services:
  wallabag:
    image: ${WALLABAG_IMAGE:-wallabag/wallabag:latest}
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=${WALLABAG_DB_DRIVER:-pdo_mysql}
      - SYMFONY__ENV__DATABASE_HOST=${WALLABAG_DB_HOST:-wallabag-db}
      - SYMFONY__ENV__DATABASE_PORT=${WALLABAG_DB_PORT:-3306}
      - SYMFONY__ENV__DATABASE_NAME=${WALLABAG_DB_NAME:-wallabag}
      - SYMFONY__ENV__DATABASE_USER=${WALLABAG_DB_USER:-wallabag}
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_DB_PASS:-wallapass}
      - SYMFONY__ENV__DATABASE_CHARSET=${WALLABAG_DB_CHARSET:-utf8mb4}
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX=${WALLABAG_DB_PREFIX:-wallabag_}
      - SYMFONY__ENV__MAILER_DSN=${WALLABAG_MAILER_DSN:-smtp://127.0.0.1}
      - SYMFONY__ENV__FROM_EMAIL=${WALLABAG_FROM_WEMAIL:-wallabag@example.com}
      - SYMFONY__ENV__DOMAIN_NAME=${WALLABAG_DOMAIN:-https://your-wallabag-instance.wallabag.org}
      - SYMFONY__ENV__SERVER_NAME=${WALLABAG_SERVER:-Your wallabag instance}
      - TZ=${WALLABAG_TZ:-America/Vancouver}
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost/api/info"]
      interval: 1m
      timeout: 3s
    volumes:
      - "${VOL_PATH:-/tmp}/wallabag:/var/www/wallabag/web/assets/images"
