---
version: '3'

networks:
  admin_web:
    external:
      name: admin_web

volumes:
  wallabag:
  wallabag-db:

services:

  wallabag:
    #https://hub.docker.com/r/wallabag/wallabag
    image: wallabag/wallabag:${WALLABAG_V}
    environment:
      - MYSQL_ROOT_PASSWORD=${WALLABAG_MYSQL_ROOT_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=${PREFIX}_wallabag-db_1
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_MYSQL_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=https://${WALLABAG_DOMAIN_NAME}
    volumes:
      - wallabag:/var/www/wallabag/web/assets/images
    networks:
      - admin_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_wallabag.rule=Host(`${WALLABAG_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_wallabag.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_wallabag.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PREFIX}_wallabag.loadbalancer.server.port=80"

  wallabag-db:
    image: mariadb:${DB_V}
    restart: always
    volumes:
      - wallabag-db:/var/lib/mysql
    networks:
      - admin_web
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: ${WALLABAG_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: wallabag
      MYSQL_PASSWORD: ${WALLABAG_MYSQL_PASSWORD}
      MYSQL_DATABASE: wallabag

  wallabag-redis:
    image: redis:alpine:5.0.9
    networks:
      - admin_web
