services:
  sonarr:
    image: ${SONARR_IMAGE}
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${VOL_PATH}/sonarr/config:/config
      - ${VOL_PATH}/sonarr/data:/data
