---
version: "3.3"

services:

  php-apache:
    image: "4lights/phpcontainer:latest"
    restart: always
    volumes:
      - "${VOL_PATH:-./data}/website:/data"
      - "${VOL_PATH:-./config}/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "${DOCKERPORT}:80"