version: '3.8'

services:
  hedgedoc:
    image: ghcr.io/hedgedoc/hedgedoc:latest
    container_name: hedgedoc
    environment:
      - CMD_DB_URL=sqlite://data/hedgedoc.db
    volumes:
      - ./data:/hedgedoc/data
    ports:
      - "3000:3000"
    restart: always

volumes:
  data:

