services:

  yourls-db:
    # https://hub.docker.com/_/mariadb/
    image: mariadb:${DB_V}
    restart: always
    volumes:
      - ${VOL_PATH:-./data}/yourls-db:/var/lib/mysql
    networks:
      - yourls-net
    environment:
      MYSQL_ROOT_PASSWORD: ${YOURLS_MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${YOURLS_MYSQL_PASSWORD}
      MYSQL_DATABASE: db_yourls
      MYSQL_USER: yourls

  yourls:
    # reference: https://github.com/matomo-org/docker/blob/master/.examples/docker-compose.yml
    image: yourls
    restart: always
    volumes:
      - ${VOL_PATH:-./data}/yourls:/var/www/html
    networks:
      - yourls-net
      - proxy
    environment:
      YOURLS_DB_HOST: ${PREFIX}_yourls-db_1
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: ${YOURLS_MYSQL_PASSWORD}
      YOURLS_DB_NAME: db_yourls
      YOURLS_SITE: https://${YOURLS_DOMAIN_NAME}
      YOURLS_USER: ${YOURLS_USER}
      YOURLS_PASS: ${YOURLS_PASS}
