---
services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:8000"
      APP_SECRET: "REPLACE_WITH_LONG_SECRET"
      DATABASE_URL: "postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
      MAIL_DRIVER: smtp
      SMTP_HOST: 
      SMTP_PORT:
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SMTP_SECURE:
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: Docmost
    ports:
      - "8000:3000"
    restart: unless-stopped
    volumes:
      - ./data/docmost/docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - ./data/docmost/db:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./data/docmost/redis:/data

