services:
  qbittorrent:
    image: ${QBT_IMAGE:-trigus42/qbittorrentvpn:latest}
    restart: ${QBT_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH}/qbit/config:/config
      - ${VOL_PATH}/qbit/downloads:/downloads
      - ${VOL_PATH}/qbit/incomplete:/incomplete
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_TYPE=wireguard
      - WEBUI_PASSWORD=${QBT_PASS:-ChangeMePass}
    ports:
      - ${QBT_PORT:-8080}:8080
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - proxy

networks:
  proxy:
    external: true
