services:
  qbittorrent:
    image: ${QBT_IMAGE:-trigus42/qbittorrentvpn:latest}
    environment:
      - VPN_TYPE=wireguard
      - WEBUI_PASSWORD=${QBT_PASS:-ChangeMePass}
    volumes:
      - "${VOL_CONFIG_PATH:-./data}/config:/config"
      - "${VOL_PATH:-./data}/downloads:/downloads"
      - "${VOL_PATH:-./data}/incomplete:/incomplete"
      - '/dev/net/tun:/dev/net/tun'
    ports:
     - 8080:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1