services:
  dumbbudget:
    image: ${DUMBBUDGET_IMAGE:-dumbwareio/dumbbudget:latest}
    restart: ${DUMBBUDGET_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/dumbbudget/data:/app/data
    environment:
      - DUMBBUDGET_PIN=${DUMBBUDGET_PIN:-ChangeThisPassword}
      - BASE_URL=${DUMBBUDGET_BASE_URL:-http://localhost:3000}
      - CURRENCY=${DUMBBUDGET_CURRENCY:-CAD}
    ports:
      - ${DUMBBUDGET_PORT:-3000}:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
