---
version: "2"

services:
  streama-db:
    image: mariadb:${DB_V}
    restart: always
    volumes:
      - streama-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${STREAMA_MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${STREAMA_MYSQL_PASSWORD}
      MYSQL_DATABASE: streama
      MYSQL_USER: streama

  streama:
    image: streama
    build: .
    restart: always
    depends_on:
      - streama-db
    volumes:
      - streama-movies:/data/streama # Change to your video folder
      - streama-appdata:/app/streama
    environment:
      ACTIVE_PROFILE: mysql
      MYSQL_HOST: ${PREFIX}_streama-db_1
      MYSQL_PORT: 3306
      MYSQL_DB: streama
      MYSQL_USER: streama
      MYSQL_PASSWORD: ${STREAMA_MYSQL_PASSWORD}
