---
version: "2"

volumes:
  strema-db:
  streama-movies:
  streama-appdata:

networks:
  admin_web:
    external:
      name: admin_web

services:
  streama-db:
    image: mariadb:${DB_V}
    restart: always
    networks:
      - admin_web
    volumes:
      - streama-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${STREAMA_MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${STREAMA_MYSQL_PASSWORD}
      MYSQL_DATABASE: streama
      MYSQL_USER: streama

  streama:
    image: streama
    build: .
    restart: always
    depends_on:
      - streama-db
    networks:
      - admin_web
    volumes:
      - streama-movies:/data/streama # Change to your video folder
      - streama-appdata:/app/streama
    environment:
      ACTIVE_PROFILE: mysql
      MYSQL_HOST: ${PREFIX}_streama-db_1
      MYSQL_PORT: 3306
      MYSQL_DB: streama
      MYSQL_USER: streama
      MYSQL_PASSWORD: ${STREAMA_MYSQL_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_streama.rule=Host(`${STREAMA_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_streama.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_streama.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PREFIX}_streama.loadbalancer.server.port=8080"
