services:
  webtop:
    image: ${WEBTOP_IMAGE:-lscr.io/linuxserver/webtop:debian-xfce}
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${WEBTOP_PUID:-1000}
      - PGID=${WEBTOP_PGID:-1000}
      - TZ=${TZ:-America/Vancouver}
      - TITLE=${WEBTOP_TITLE:-Webtop}
    volumes:
      - "${VOL_PATH:-/tmp}/webtop:/config"
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "4gb"
    restart: unless-stopped
