################################################################################
# Joomla
# Update the .env file
#
# Version 1
################################################################################
version: '3.3'

volumes:
  mariadb:
  joomla:

networks:
  admin_web:
    external:
      name: admin_web

services:

  mariadb:
    image: mariadb:${LAMPDB_V}
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - admin_web
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: joomla
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: joomla

  memcached:
    image: memcached:${MEM_V}
    restart: always
    networks:
      - admin_web

  lamp:
    image: nick/ubuntu-apache-php:latest
    restart: always
    links:
      - mariadb
    networks:
      - admin_web
    volumes:
      - joomla:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_lamp.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_lamp.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_lamp.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PREFIX}_lamp.loadbalancer.server.port=80"
