services:
  whisparr:
    image: ${WHISPARR_IMAGE:-ghcr.io/hotio/whisparr:release}
    restart: ${WHISPARR_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/whisparr/config:/config
      - ${VOL_PATH:-/data}/whisparr/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-America/Vancouver}
    ports:
      - "${WHISPARR_PORT:-6969}:6969"
    networks:
      - proxy

networks:
  proxy:
    external: true
