# Heimdall
services:
  heimdall:
    image: ${HEIMDALL_IMAGE}
    restart: ${HEIMDALL_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-./data}/heimdall:/config
    environment:
      - PGID=${HEIMDALL_PGID:-1000}
      - PUID=${HEIMDALL_PUID:-1000}
      - TZ=${TZ:-America/Vancouver}
    ports:
      - ${HEIMDALL_PORT:-8000}:80
    networks:
      - proxy

networks:
  proxy:
    external: true
