services:
  penpot-postgres:
    image: ${PENPOT_POSTGRES_IMAGE:-postgres:15}
    restart: ${PENPOT_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/penpot/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    networks:
      - internal

  penpot-redis:
    image: ${PENPOT_REDIS_IMAGE:-redis:7.2}
    restart: ${PENPOT_RESTART:-unless-stopped}
    networks:
      - internal

  penpot-mailcatch:
    image: ${PENPOT_MAILCATCH_IMAGE:-sj26/mailcatcher:latest}
    restart: ${PENPOT_RESTART:-unless-stopped}
    networks:
      - internal

  penpot-backend:
    image: ${PENPOT_BACKEND_IMAGE:-penpotapp/backend:latest}
    restart: ${PENPOT_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/penpot/assets:/opt/data/assets
    environment:
      - PENPOT_FLAGS=${PENPOT_FLAGS:-disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies}
      - PENPOT_PUBLIC_URI=${PENPOT_PUBLIC_URI:-http://localhost:9001}
      - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=${PENPOT_BODY_SIZE:-31457280}
      - PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE=${PENPOT_MULTIPART_SIZE:-367001600}
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_SMTP_DEFAULT_FROM=${PENPOT_SMTP_FROM:-no-reply@example.com}
      - PENPOT_SMTP_HOST=penpot-mailcatch
      - PENPOT_SMTP_PORT=1025
      - PENPOT_SMTP_TLS=false
      - PENPOT_SMTP_SSL=false
      - PENPOT_TELEMETRY_ENABLED=${PENPOT_TELEMETRY:-true}
    networks:
      - internal
    depends_on:
      - penpot-postgres
      - penpot-redis

  penpot-exporter:
    image: ${PENPOT_EXPORTER_IMAGE:-penpotapp/exporter:latest}
    restart: ${PENPOT_RESTART:-unless-stopped}
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
      - PENPOT_REDIS_URI=redis://penpot-redis/0
    networks:
      - internal

  penpot-frontend:
    image: ${PENPOT_FRONTEND_IMAGE:-penpotapp/frontend:latest}
    restart: ${PENPOT_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/penpot/assets:/opt/data/assets
    ports:
      - "${PENPOT_PORT:-9001}:8080"
    networks:
      - proxy
      - internal
    depends_on:
      - penpot-backend
      - penpot-exporter

networks:
  proxy:
    external: true
  internal:
