services:
  grocy:
    image: ${GROCY_IMAGE:-lscr.io/linuxserver/grocy:latest}
    restart: ${GROCY_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/grocy/config:/config
    environment:
      - TZ=${TZ:-America/Vancouver}
      - PUID=${GROCY_PUID:-1000}
      - PGID=${GROCY_PGID:-1000}
    ports:
      - ${GROCY_PORT:-9283}:80
    networks:
      - proxy

networks:
  proxy:
    external: true
