services:
  filebrowser:
    image: ${FILEBROWSER_IMAGE:-gtstef/filebrowser:latest}
    volumes:
      - ${VOL_PATH:-./data}/storage:/srv
      - ${VOL_PATH:-./data}/filebrowser/root:/home/filebrowser/data
      - ${VOL_CONFIG_PATH:-./config}/config.yaml:/home/filebrowser/config.yaml
    environment:
      FILEBROWSER_CONFIG: "${FILEBROWSER_CONFIG:-/home/filebrowser/config.yaml}"
      FILEBROWSER_ADMIN_PASSWORD: ${FILEBROWSER_ADMIN_PASSWORD:-admin}
      TZ: ${TZ:-America/Vancouver}

