version: '3.8'

services:
  filebrowser:
    image: ${FILEBROWSER_IMAGE:-filebrowser/filebrowser:latest}
    restart: unless-stopped
    volumes:
      - ${VOL_CONFIG_PATH:-./config}/filebrowser.json:/.filebrowser.json
      - ${VOL_PATH:-./data}/filebrowser/filebrowser.db:/database.db
      - ${VOL_PATH:-./data}/filebrowser-root:/srv
