services:
  piwigo:
    image: ${PIWIGO_IMAGE:-lscr.io/linuxserver/piwigo:latest}
    restart: unless-stopped
    environment:
      - PUID=${PIWIGO_PUID:-1000}
      - PGID=${PIWIGO_PGID:-1000}
      - TZ=${TZ:-America/Vancouver}
    volumes:
      - ${VOL_PATH:-./data}/piwigo:/config
      - ${VOL_PATH:-./data}/gallery:/gallery
