services:
  duplicati:
    image: ${DUPLICATI_IMAGE:-duplicati/duplicati:latest}
    volumes:
      - ${VOL_PATH:-./data}/duplicati/config:/data
      - ${VOL_PATH:-./data}/duplicati/backups:/backups
      - ${VOL_PATH:-./data}/duplicati/source:/source:ro
      # Add More sorces, for example: - /NAS:/source_nas:ro
      - ${VOL_PATH:-./data}/duplicati/restore:/restore
    environment:
      TZ: ${TZ:-America/Vancouver}
      SETTINGS_ENCRYPTION_KEY: "${DUPLICATI_KEY:-ThisNeedsToChange}"
      DUPLICATI__WEBSERVICE_PASSWORD: "${DUPLICATI_PASS:-changeMe}"
    restart: unless-stopped
    ports:
      - "8200:8200"