services:
  homepage:
    image: ${HOMEPAGE_IMAGE:-ghcr.io/gethomepage/homepage:latest}
    restart: ${HOMEPAGE_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/homepage/config:/app/config
    environment:
      - TZ=${TZ:-America/Vancouver}
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
