services:
  vaultwarden:
    image: ${VAULT_IMAGE:-vaultwarden/server:latest}
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "${VAULT_WEBSOCKET_ENABLED:-true}" # Enable WebSocket notifications
      SIGNUPS_ALLOWED: "${VAULT_SIGNUPS_ALLOWED:-false}" # Disable new user signups
      DOMAIN: ${VAULT_DOMAIN:-example.com}
      ADMIN_TOKEN: "${VAULT_ADMIN_TOKEN:-changeme}"
      SMTP_HOST: ${SMTP_HOST:-smtp.example.com}
      SMTP_FROM: ${SMTP_FROM:-no-reply@example.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURITY: ${SMTP_SECURITY:-tls}
      SMTP_USERNAME: ${SMTP_USERNAME:-smtp_user@example.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-SuperSecretPassword123}
    volumes:
      - "${VOL_PATH:-./data}/vault-data:/data"
