services:
  vaultwarden:
    image: ${VAULT_IMAGE:-vaultwarden/server:latest}
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "${VAULT_WEBSOCKET_ENABLED:-true}" # Enable WebSocket notifications
      SIGNUPS_ALLOWED: "${VAULT_SIGNUPS_ALLOWED:-false}" # Disable new user signups
      DOMAIN: ${VAULT_DOMAIN}
      ADMIN_TOKEN: "${VAULT_ADMIN_TOKEN}"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - "${VOL_PATH:-./data}/vault-data:/data"


