################################################################################
# Gitea
# make sure you use the $PREFIX from .env for project_name
# docker-compose -p project_name up -d
#
# Importing directly to the db (phpmydadmin)
# you have to run the following in the container:
# php artisan bookstack:regenerate-permissions
#
# Version 1
################################################################################
version: '3.3'

volumes:
  gitea:

networks:
  traefik_web:
    external:
      name: ${NETWORK_NAME}

services:

  gitea:
    # https://hub.docker.com/r/gitea/gitea
    image: gitea/gitea:${GITEA_V}
    networks:
      - ${NETWORK_NAME}
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_gitea.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_gitea.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_gitea.tls=true"
      - "traefik.http.services.${PREFIX}_gitea.loadbalancer.server.port=3000"
