services:

  gitea:
    image: ${GITEA_IMAGE:-gitea/gitea:latest}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=${GITEA_DB_HOST:-gitea-mariadb:3306}
      - DB_NAME=gitea
      - DB_USER=gitea
      - SSH_DOMAIN=${GITEA_SSH_DOMAIN:-example.com}
      - ENABLE_SWAGGER="true"
      - MAX_RESPONSE_ITEMS="15"
    restart: always
    volumes:
      - ${VOL_PATH:-./data}/gitea:/data
    ports:
      - "${GITEA_PORT}:22"
      - "${GITEA_WEB_PORT}:3000"
