# Gitea

services:

  gitea:
    image: ${GITEA_IMAGE}
    restart: ${GITEA_RESTART:-always}
    volumes:
      - ${VOL_PATH}/gitea:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=${GITEA_DB_HOST:-gitea-db:3306}
      - GITEA__database__NAME=${GITEA_DB_NAME:-gitea}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASS:-changeMe}
      - GITEA__server__SSH_DOMAIN=${GITEA_SSH_DOMAIN}
      - GITEA__server__PROTOCOL=http
      - GITEA__server__DOMAIN=${GITEA_DOMAIN:-git.example.com}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL:-https://git.example.com/}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT:-22}
      - ENABLE_SWAGGER=true
      - MAX_RESPONSE_ITEMS=15
      
    ports:
      - ${GITEA_HOST_SSH_PORT:-22}:${GITEA_SSH_PORT:-22}
      - ${GITEA_WEB_PORT:-3000}:3000
    networks:
      - proxy
      - db
    depends_on:
      - gitea-db

  gitea-db:
    image: ${MARIA_IMAGE:-mariadb:latest}
    restart: ${GITEA_RESTART:-always}
    volumes:
      - ${VOL_PATH}/gitea-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_ROOT:-changeMe}
      MYSQL_USER: ${GITEA_DB_USER:-gitea}
      MYSQL_PASSWORD: ${GITEA_DB_PASS:-changeMe}
      MYSQL_DATABASE: ${GITEA_DB_NAME:-gitea}
      TZ: ${TZ:-America/Vancouver}
    networks:
      - db

networks:
  proxy:
    external: true
  db:
    driver: bridge
