services:
  stash:
    image: ${STASHAPP_IMAGE:-stashapp/stash:latest}
    restart: unless-stopped
    environment:
      - STASH_CACHE=${STASHAPP_STASH_CACHE:-/cache/}
      - STASH_DOMAIN_NAME=${STASHAPP_STASH_DOMAIN_NAME:-stash.yourdomain.ca}
      - STASH_GENERATED=${STASHAPP_STASH_GENERATED:-/generated/}
      - STASH_METADATA=${STASHAPP_STASH_METADATA:-/metadata/}
      - STASH_STASH=${STASHAPP_STASH_STASH:-/data/}
    volumes:
      - ${VOL_PATH:-./data}/stash-cache:/cache
      - ${VOL_PATH:-./data}/stash-generated:/generated
      - ${VOL_PATH:-./data}/stash-metadata:/metadata
      - ${VOL_PATH:-./data}/stash-root:/root
      - ${VOL_PATH:-./data}/stash-video:/data
      - /etc/localtime:/etc/localtime:ro
