version: '3.4'

services:
  stash:
    image: ${STASH_IMAGE:-stashapp/stash:v0.26.2}
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: ${MAX_SIZE:-200m}
    restart: unless-stopped
    environment:
      - STASH_STASH=${STASH_STASH:-/data/}
      - STASH_GENERATED=${STASH_GENERATED:-/generated/}
      - STASH_METADATA=${STASH_METADATA:-/metadata/}
      - STASH_CACHE=${STASH_CACHE:-/cache/}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/video:/data"
      - "./data/metadata:/metadata"
      - "./data/cache:/cache"
      - "./data/generated:/generated"
      - "./data/root:/root"
    # Uncomment and use if needed
    # network_mode: "host"


