################################################################################
# Stash
# make sure you use the $PREFIX from .env for project_name
# docker-compose -p project_name up -d
#
# Version 1
################################################################################
version: '2'

volumes:
  stash:
  stash-metadata:
  stash-cache:
  stash-generated:

networks:
  admin_web:
    external:
      name: admin_web

services:
  stash:
    # https://hub.docker.com/r/stashapp/stash
    image: stashapp/stash:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "200m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    networks:
      - admin_web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - stash:/data
      - stash-metadata:/metadata
      - stash-cache:/cache
      - stash-generated:/generated
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_stash.rule=Host(`${STASH_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_stash.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_stash.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PREFIX}_stash.loadbalancer.server.port=9999"
