services:
  handbrake:
    image: ${HANDBRAKE_IMAGE:-jlesage/handbrake:latest}
    volumes:
      - "${VOL_PATH:-./data}/handbrake/ghb-config:/config"
      - "${VOL_PATH:-./data}/handbrake/storage:/storage"
      - "${VOL_PATH:-./data}/handbrake/complete:/output"
      - "${VOL_PATH:-./data}/handbrake/watch:/watch"
      - "${VOL_PATH:-./data}/handbrake/watch2:/watch2"
      - "${VOL_PATH:-./data}/handbrake/trash:/trash"
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      - "5800:5800"
    # Below for GPU
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
