---
version: "3"

services:
  handbrake:
    image: ${HANDBRAKE_IMAGE:-jlesage/handbrake:latest}
    volumes:
      - "${VOL_CONFIG_PATH:-./config}/preferences.json:/config/ghb/preferences.json"
      - "${VOL_CONFIG_PATH:-./config}/presets.json:/config/ghb/presets.json"
      - "${VOL_PATH:-./data}/handbrake/storage:/storage"
      - "${VOL_PATH:-./data}/handbrake/complete:/output"
    restart: "unless-stopped"
    ports:
      - "5800:5800"
