services:
  ntfy:
    image: ${NTFY_IMAGE:-binwiederhier/ntfy}
    restart: unless-stopped
    command:
      - serve
    environment:
      - NTFY_BASE_URL=${NTFY_BASE_URL:-http://localhost}
      - NTFY_CACHE_FILE=${NTFY_CACHE_FILE:-/var/lib/ntfy/cache.db}
      - NTFY_AUTH_FILE=${NTFY_AUTH_FILE:-/var/lib/ntfy/auth.db}
      - NTFY_AUTH_DEFAULT_ACCESS=${NTFY_AUTH_DEFAULT_ACCESS:-deny-all}
      - NTFY_BEHIND_PROXY=${NTFY_BEHIND_PROXY:-true}
      - NTFY_ATTACHMENT_CACHE_DIR=${NTFY_ATTACHMENT_CACHE_DIR:-/var/lib/ntfy/attachments}
      - NTFY_ENABLE_LOGIN=${NTFY_ENABLE_LOGIN:-true}
      - TZ=${TZ:-UTC}
    volumes:
      - ${VOL_PATH:-./data}/ntfy-cache/ntfy:/var/cache/ntfy
      - ${VOL_PATH:-./data}/ntfy:/etc/ntfy
      - ${VOL_PATH:-./data}/ntfy-var:/var/lib/ntfy
