version: "2.3"

#####################################################################################################################################
# NTFY
#
# Compose file: https://docs.ntfy.sh/install/#docker
# Config: https://docs.ntfy.sh/config/
# Ports: 80
# ntfy user add your_name
# ntfy user change-role your_name admin
#####################################################################################################################################

services:
  ntfy:
    image: binwiederhier/ntfy
    command:
      - serve
    volumes:
      - ./data/cache/ntfy:/var/cache/ntfy
      - ./data/ntfy:/etc/ntfy
      - ./data/ntfy-var:/var/lib/ntfy
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      NTFY_BASE_URL: http://localhost
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: "true"
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: "true"
    healthcheck: # optional: remember to adapt the host:port to your environment
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 80:80
    restart: unless-stopped