services:
  pihole:
    image: ${PIHOLE_IMAGE:-pihole/pihole:latest}
    restart: ${PIHOLE_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH}/pihole/etc:/etc/pihole
      - ${VOL_PATH}/pihole/dnsmasq:/etc/dnsmasq.d
    environment:
      - TZ=${TZ:-America/Vancouver}
      - FTLCONF_dns_listeningMode=ALL
      - FTLCONF_webserver_port=8080o,[::]:8080o,8443os,[::]:8443os
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
