services:
  nextcloud-db:
    image: ${MARIADB_IMAGE:-mariadb:latest}
    restart: ${MARIADB_RESTART:-unless-stopped}
    command: >
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --innodb-file-per-table=1
      --skip-innodb-read-only-compressed
    volumes:
      - ${VOL_PATH}/nextcloud/db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${NEXTCLOUD_DB:-nextcloud}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-ChangeThisPassword}
      - MARIADB_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - MARIADB_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-ChangeThisPassword}
    networks:
      - internal

  nextcloud:
    image: ${NEXTCLOUD_IMAGE:-nextcloud:latest}
    restart: ${NEXTCLOUD_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH}/nextcloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-ChangeThisPassword}
      - MYSQL_DATABASE=${NEXTCLOUD_DB:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - MYSQL_HOST=${NEXTCLOUD_DB_HOST:-nextcloud-db}
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
