################################################################################
# Nextcloud
#
# Version 1
################################################################################
version: '3.3'

volumes:
  nextcloud-db:
  nextcloud:

networks:
  admin_web:
    external:
      name: admin_web

services:

  nextcloud-db:
    image: mariadb:${DB_V}
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - admin_web
    environment:
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${NEXTCLOUD_MYSQL_PASSWORD}
      MYSQL_DATABASE: db_nextcloud

  nextcloud:
    image: nextcloud:${NEXTCLOUD_V}
    stdin_open: true
    tty: true
    networks:
      - admin_web
    restart: always
    links:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_nextcloud.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PREFIX}_nextcloud.loadbalancer.server.port=80"
