version: '3.3'

volumes:
  mariadb:
  nextcloud:
  document_data:
  document_log:

networks:
  traefik_web:
    external:
      name: traefik_web

services:

  mariadb:
    image: mariadb:10.4.11
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - traefik_web
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: nextcloud

  nextcloud:
    image: nextcloud:18.0.3-apache
    stdin_open: true
    tty: true
    networks:
      - traefik_web
    restart: always
    depends_on:
      - mariadb
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
