services:
  nextcloud:
    image: ${NEXTCLOUD_IMAGE:-nextcloud:latest}
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-password}
      - MYSQL_DATABASE=${NEXTCLOUD_DB:-nextcloud}
      - MYSQL_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - MYSQL_HOST=${NEXTCLOUD_DB_HOST:-nextcloud-db}
    volumes:
      - ${VOL_PATH:-./data}/nextcloud:/var/www/html
