services:
  radarr:
    image: ${RADARR_IMAGE}
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${VOL_PATH}/radarr/config:/config
      - ${VOL_PATH}/radarr/data:/data