services:
  redis:
    image: ${REDIS_IMAGE:-redis:alpine}
    restart: ${REDIS_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/redis:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    internal: true
