services:
  homepage:
    image: ${HOMEPAGE_IMAGE:-ghcr.io/gethomepage/homepage:latest}
    restart: unless-stopped
    volumes:
      - ${VOL_CONFIG_PATH:-./config}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
