services:
  directus:
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - "8000:8055"
    environment:
      SECRET: ${DIRECTUS_SECRET:-0123456789}
      DB_CLIENT: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE:-dbname}
      DB_USER: ${MARIADB_USER:-db_username}
      DB_PASSWORD: ${MARIADB_PASSWORD:-db_password}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-noreply@example.com}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD:-change_me_to_admin_pass}
      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL:-http://localhost:8055}
    depends_on:
      - mariadb
      - redis
    volumes:
      - ${VOL_PATH:-./data}/directus/uploads:/directus/uploads
      - ${VOL_PATH:-./data}/directus/extensions:/directus/extensions
      - ${VOL_PATH:-./data}/directus/templates:/directus/templates
