services:
  directus:
    image: directus/directus
    restart: unless-stopped
    ports:
      - "8000:8055"
    environment:
      SECRET: ChangeMeTo32
      DB_CLIENT: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directuspassword
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: directus
      MARIADB_USER: directus
      MARIADB_PASSWORD: directuspassword
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data/directus_db_data:/var/lib/mysql

