services:
  mariadb:
    image: ${MARIADB_IMAGE:-mariadb:10.11}
    restart: ${DIRECTUS_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/directus/db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE:-directus}
      - MARIADB_USER=${MARIADB_USER:-directus}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-ChangeThisPassword}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-ChangeThisPassword}
    networks:
      - internal

  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    restart: ${DIRECTUS_RESTART:-unless-stopped}
    networks:
      - internal

  directus:
    image: ${DIRECTUS_IMAGE:-directus/directus:latest}
    restart: ${DIRECTUS_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/directus/uploads:/directus/uploads
      - ${VOL_PATH:-/data}/directus/extensions:/directus/extensions
      - ${VOL_PATH:-/data}/directus/templates:/directus/templates
    environment:
      - SECRET=${DIRECTUS_SECRET:-ChangeThisPassword}
      - DB_CLIENT=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=${MARIADB_DATABASE:-directus}
      - DB_USER=${MARIADB_USER:-directus}
      - DB_PASSWORD=${MARIADB_PASSWORD:-ChangeThisPassword}
      - ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL:-noreply@example.com}
      - ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD:-ChangeThisPassword}
      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - CACHE_STORE=redis
      - REDIS=redis://redis:6379
      - PUBLIC_URL=${DIRECTUS_PUBLIC_URL:-http://localhost:8055}
    ports:
      - "${DIRECTUS_PORT:-8000}:8055"
    networks:
      - proxy
      - internal
    depends_on:
      - mariadb
      - redis

networks:
  proxy:
    external: true
  internal:
