services:
  headscale:
    image: ${HEADSCALE_IMAGE:-headscale/headscale:latest}
    restart: ${HEADSCALE_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/headscale/config:/etc/headscale
      - ${VOL_PATH:-/data}/headscale/data:/var/lib/headscale
      - ${VOL_PATH:-/data}/headscale/logs:/var/log/headscale
    environment:
      - TZ=${TZ:-America/Vancouver}
      - HEADSCALE_LOG_LEVEL=${HEADSCALE_LOG_LEVEL:-info}
    networks:
      - proxy
      - internal
    command:
      - headscale
      - serve

  headscale-ui:
    image: ${HEADSCALE_UI_IMAGE:-goodieshq/headscale-admin:latest}
    restart: ${HEADSCALE_UI_RESTART:-unless-stopped}
    environment:
      - TZ=${TZ:-America/Vancouver}
      - HEADSCALE_URL=http://headscale:8080
    networks:
      - proxy
      - internal
    depends_on:
      - headscale

networks:
  proxy:
    external: true
  internal:
