################################################################################
# phpmyadmin
# make sure you use the $PREFIX from .env for project_name
# docker-compose -p project_name up -d
#
# Version 1
################################################################################
version: '2'

networks:
  admin_web:
    external:
      name: admin_web

services:

  # It's only exposed if someone knows the ip
  phpmyadmin:
    #https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_V}
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=200M
    restart: unless-stopped
    networks:
      - admin_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_phpmyadmin.rule=Host(`${PHPMYADMIN_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_phpmyadmin.tls=true"
      - "traefik.http.services.${PREFIX}_phpmyadmin.loadbalancer.server.port=80"
