services:
  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE:-phpmyadmin/phpmyadmin:latest}
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=${PHPMYADMIN_PMA_ARBITRARY:-1}
      - PMA_HOST=${PHPMYADMIN_PMA_HOST:-mariadb}
      - PMA_USER=${PHPMYADMIN_PMA_USER:-root}
      - PMA_PASSWORD=${MARIADB_MARIADB_ROOT_PASSWORD:-ChangeThisPassword}
      - UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT:-200M}  
      