services:
  jellyfin:
    image: ${JELLYFIN_IMAGE:-jellyfin/jellyfin:latest}
    restart: ${JELLYFIN_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/jellyfin/cache:/cache
      - ${VOL_PATH:-/data}/jellyfin/config:/config
      - ${VOL_PATH:-/data}/jellyfin/media/books:/books
      - ${VOL_PATH:-/data}/jellyfin/media/movies:/movies
      - ${VOL_PATH:-/data}/jellyfin/media/music:/music
      - ${VOL_PATH:-/data}/jellyfin/media/photos:/photos
      - ${VOL_PATH:-/data}/jellyfin/media/shows:/shows
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL:-http://localhost:8096}
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
