# InvokeAI Docker Compose
services:
  invokeai:
    image: ${INVOKEAI_IMAGE:-ghcr.io/invoke-ai/invokeai:latest}
    restart: ${INVOKEAI_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-./data}/invokeai:/invokeai
    environment:
      - INVOKEAI_ROOT=/invokeai
      - INVOKEAI_PORT=${INVOKEAI_PORT:-9090}
    ports:
      - "${INVOKEAI_PORT:-9090}:9090"
    gpus: all
