services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17-alpine}
    restart: ${OPENARCHIVER_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/openarchiver/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-open_archive}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    networks:
      - internal

  valkey:
    image: ${VALKEY_IMAGE:-valkey/valkey:8-alpine}
    restart: ${OPENARCHIVER_RESTART:-unless-stopped}
    command: valkey-server --requirepass ${REDIS_PASSWORD:-RedisPasswordChangeMe}
    volumes:
      - ${VOL_PATH:-/data}/openarchiver/valkeydata:/data
    networks:
      - internal

  meilisearch:
    image: ${MEILISEARCH_IMAGE:-getmeili/meilisearch:v1.15}
    restart: ${OPENARCHIVER_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/openarchiver/meilidata:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-aSampleMasterKey}
    networks:
      - internal

  tika:
    image: ${TIKA_IMAGE:-apache/tika:3.2.2.0-full}
    restart: ${OPENARCHIVER_RESTART:-unless-stopped}
    networks:
      - internal

  open-archiver:
    image: ${OPENARCHIVER_IMAGE:-logiclabshq/open-archiver:latest}
    restart: ${OPENARCHIVER_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/openarchiver/archiver-data:/var/data/open-archiver
    ports:
      - "${OPENARCHIVER_PORT:-3000}:3000"
    networks:
      - proxy
      - internal
    depends_on:
      - postgres
      - valkey
      - meilisearch

networks:
  proxy:
    external: true
  internal:
