services:

  suitecrm:
    image: bitnami/suitecrm:latest
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=suitecrm
      - SUITECRM_DATABASE_PASSWORD=${SUITECRM_DB_PASSWORD}
      - SUITECRM_DATABASE_NAME=suitecrm_db
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_USERNAME=${SUITECRM_USER}
      - SUITECRM_PASSWORD=${SUITECRM_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    volumes:
      - ${VOL_PATH:-./data}/suitecrm_data:/bitnami/suitecrm
    restart: unless-stopped

