version: '3.1'

services:

  suitecrm:
    image: bitnami/suitecrm:latest
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=suitecrm
      - SUITECRM_DATABASE_PASSWORD=suitecrm_password
      - SUITECRM_DATABASE_NAME=suitecrm_db
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_USERNAME=nick
      - SUITECRM_PASSWORD=yeoman
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    volumes:
      - suitecrm_data:/bitnami/suitecrm
    restart: unless-stopped

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_USER=suitecrm
      - MARIADB_PASSWORD=suitecrm_password
      - MARIADB_DATABASE=suitecrm_db
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: unless-stopped

volumes:
  suitecrm_data:
    driver: local
  mariadb_data:
    driver: local
