services:
  nocodb:
    image: ${NOCODB_IMAGE:-nocodb/nocodb:latest}
    restart: ${NOCODB_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/nocodb:/usr/app/data
    ports:
      - "${NOCODB_PORT:-8080}:8080"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
