services:
  readarr:
    image: ${READARR_IMAGE:-ghcr.io/hotio/readarr:release}
    restart: ${READARR_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/readarr/config:/config
      - ${VOL_PATH:-/data}/readarr/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-America/Vancouver}
    ports:
      - "${READARR_PORT:-8787}:8787"
    networks:
      - proxy

networks:
  proxy:
    external: true
