services:

  mariadb:
    image: ${MARIADB_IMAGE:-mariadb:latest}
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MARIADB_DATABASE=${MARIADB_MARIADB_DATABASE:-mydb}
      - MARIADB_ROOT_PASSWORD=${MARIADB_MARIADB_ROOT_PASSWORD:-ChangeThisPassword}
      - MARIADB_USER=${MARIADB_MARIADB_USER:-dbuser}
      - MARIADB_PASSWORD=${MARIADB_MARIADB_PASSWORD:-AlsoChangeThisPassword}
    volumes:
      - ${VOL_PATH:-./data/}/mariadb:/var/lib/mysql
