services:
  jellyfin:
    image: ${JELLYFIN_IMAGE:-jellyfin/jellyfin:latest}
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl:-http://localhost:8096}
    volumes:
      - ${VOL_PATH:-./data}/jellyfin-cache:/cache
      - ${VOL_PATH:-./data}/jellyfin-config:/config
      - ${VOL_PATH:-./data}/jellyfin-content/books:/books
      - ${VOL_PATH:-./data}/jellyfin-content/media:/media
      - ${VOL_PATH:-./data}/jellyfin-content/movies:/movies
      - ${VOL_PATH:-./data}/jellyfin-content/music:/music
      - ${VOL_PATH:-./data}/jellyfin-content/musicvideos:/musicvideos
      - ${VOL_PATH:-./data}/jellyfin-content/photos:/photos
      - ${VOL_PATH:-./data}/jellyfin-content/shows:/shows
