---
version: "3"

###########################################################################################################################
# Jellyfin
# 
# LINKS
# * [DockerHub jellyfin](https://hub.docker.com/r/jellyfin/jellyfin)
# * [DockerHub Mariadb](https://hub.docker.com/_/mariadb/)
# * [Docs](https://jellyfin.org/docs/)
#
# Notes:
# Static Ports
# * 8096/tcp is used by default for HTTP traffic. You can change this in the dashboard.
# * 8920/tcp is used by default for HTTPS traffic. You can change this in the dashboard.
# * 1900/udp is used for service auto-discovery. This is not configurable.
# * 7359/udp is also used for auto-discovery. This is not configurable.
#
# SAMPLE ENV
# APP_URL: http://localhost:8096
###########################################################################################################################

services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - ./data/content/media:/media
      - ./data/content/books:/books
      - ./data/content/movies:/movies
      - ./data/content/music:/music
      - ./data/content/musicvideos:/musicvideos
      - ./data/content/photos:/photos
      - ./data/content/shows:/shows
    ports: 
      - "8096:8096"
    environment:
      - JELLYFIN_PublishedServerUrl=${APP_URL:-http://localhost:8096}
