services:
  spotdl:
    image: ${SPOTDL_IMAGE:-spotdl/spotify-downloader:latest}
    restart: ${SPOTDL_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/spotdl/music:/music
    ports:
      - "${SPOTDL_PORT:-8800}:8800"
    networks:
      - proxy
    command:
      - web

networks:
  proxy:
    external: true
