version: '3'

services:
  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    ports:
      - 9000:9000
    environment:
      - AGENT_SECRET=${AGENT_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${VOL_PATH:-./config}/portainer:/data"
    restart: always
    networks:
      - portainer-net
  
  portainer-agent:
    image: ${PORTAINER_AGENT_IMAGE:-portainer/agent:latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_SECRET=${AGENT_SECRET}
    ports:
      - 9001:9001
    restart: always
    networks:
      - portainer-net

