################################################################################
# Portainer
# You should only need one instance of this running
# Change .env then
# docker-compose up -d
#
# Version 2
################################################################################

version: '2'

volumes:
  portainer:

networks:
  admin_web:
    external:
      name: admin_web

services:

  portainer:
    image: portainer/portainer:${PORTAINER_V}
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - admin_web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates/templates.json:/templates.json
      - portainer:/data
    command: -H unix:///var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
