# Ollama GPU
services:
  ollama:
    image: ollama/ollama
    volumes:
      - ${VOL_PATH}/ollama:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "11434:11434"

  webui:
    image: ${WEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}
    volumes:
      - "${VOL_PATH:-/data}/webui:/root/.cache"
      - "${VOL_PATH:-/data}/open-webui:/app/backend/data"
    environment:
      - WEBUI_URL=${WEBUI_URL:-http://localhost:8080}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:?must_be_set}
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "${WEBUI_PORT:-8080}:8080"
