#####################################################################################################################################
# Memos
#
# https://www.usememos.com/docs/install/self-hosting
#####################################################################################################################################

services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - 5230:5230