################################################################################
# matomo
#
# Sample .env
#
# MATOMO_MYSQL_ROOT_PASSWORD=ChangeRootPass
# MATOMO_MYSQL_PASSWORD=ChangeThisPassword
# NETWORKNAME=admin_web
# DB_V=11.3.2
################################################################################
version: '3.8'

networks:
  default:
    external:
      name: ${NETWORKNAME:-default} 

services:

  matomodb:
    image: mariadb:${DB_V}
    restart: always
    volumes:
      - ./data/matomodb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_MYSQL_ROOT_PASSWORD:-12345678}
      MYSQL_PASSWORD: ${MATOMO_MYSQL_PASSWORD:-987654321}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo

  # https://hub.docker.com/_/matomo/
  matomo:
    image: matomo:${MATOMO_V}
    volumes:
      - ./data/matomo:/var/www/html
      - ./data/matomoconfig:/var/www/html/config
      - ./data/matomologs:/var/www/html/logs
    restart: always
