################################################################################
# Joomla
# Update the .env file
#
# Version 1
################################################################################
version: '3.3'

volumes:
  lap:

networks:
  admin_web:
    external:
      name: admin_web

services:

  lap:
    image: nick/ubuntu-apache-php:latest
    restart: always
    networks:
      - admin_web
    volumes:
      - lap:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PREFIX}_lap.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PREFIX}_lap.entrypoints=websecure"
      - "traefik.http.routers.${PREFIX}_lap.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PREFIX}_lap.loadbalancer.server.port=80"
