services:
  etherpad:
    image: ${ETHERPAD_IMAGE:-node:18-slim}
    restart: ${ETHERPAD_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/etherpad:/home/etherpad
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-America/Vancouver}
      - ETHERPAD_DEFAULT_TITLE=${ETHERPAD_DEFAULT_TITLE:-Etherpad}
      - ETHERPAD_DEFAULT_TEXT=${ETHERPAD_DEFAULT_TEXT:-Welcome to Etherpad!}
      - ETHERPAD_ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD:-ChangeThisPassword}
    ports:
      - "${ETHERPAD_PORT:-9001}:9001"
    networks:
      - proxy
      - internal
    command:
      - docker-entrypoint.sh
      - /bin/bash
      - -c
      - "npm install -g git+https://github.com/etherpad/etherpad-lite.git && cp -r /usr/local/lib/node_modules/etherpad-lite/* /home/etherpad/ && chmod -R 775 /home/etherpad/ && ls -la /home/etherpad/"

networks:
  proxy:
    external: true
  internal:
    internal: true
