services:
  minio:
    image: ${MINIO_IMAGE:-quay.io/minio/minio}
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-aministrator}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-01234567890123456}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL:-https://s3.example.com}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:-https://console.s3.example.com}
      - CONSOLE_SECURE_TLS_REDIRECT=${MINIO_CONSOLE_SECURE_TLS_REDIRECT:-off}
    volumes:
      - ${VOL_PATH:-./data/}/minio:/data
