# ARCHIVEBOX

services:
  archivebox:
    image: ${ARCHIVEBOX_IMAGE:-archivebox/archivebox:stable}
    restart: ${ARCHIVEBOX_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH}/archivebox:/data
    environment:
      - ARCHIVEBOX_UID=1000
      - ARCHIVEBOX_GID=1000
      - PYTHONUNBUFFERED=1
    networks:
      - proxy
    command:  server --quick-init 0.0.0.0:8000

networks:
  proxy:
    external: true
