services:
  mailarchiver:
    image: ${MAILARCHIVER_IMAGE:-s1t5/mailarchiver:latest}
    restart: ${MAILARCHIVER_RESTART:-unless-stopped}
    environment:
      - ConnectionStrings__DefaultConnection=Host=mailarchiver-db;Database=MailArchiver;Username=mailuser;Password=${MAILARCHIVER_DB_PASSWORD:-ChangeThisPassword}
      - Authentication__Username=${MAILARCHIVER_USERNAME:-admin}
      - Authentication__Password=${MAILARCHIVER_PASSWORD:-ChangeThisPassword}
      - TimeZone__DisplayTimeZoneId=${MAILARCHIVER_TIMEZONE:-America/Vancouver}
    ports:
      - ${MAILARCHIVER_PORT:-5000}:5000
    networks:
      - proxy
      - internal
    depends_on:
      - mailarchiver-db

  mailarchiver-db:
    image: ${POSTGRES_IMAGE:-postgres:17-alpine}
    restart: ${MAILARCHIVER_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/mailarchiver/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=MailArchiver
      - POSTGRES_USER=mailuser
      - POSTGRES_PASSWORD=${MAILARCHIVER_DB_PASSWORD:-ChangeThisPassword}
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
