services:
  proxy:
    image: ${PROXY_IMAGE:-jc21/nginx-proxy-manager:latest}
    restart: unless-stopped
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "${VOL_PATH:-/data}/nginx-proxy-manager/data:/data"
      - "${VOL_PATH:-/data}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt"
      - "${LOG_PATH:-/var/log/containers/nginx-proxy-manager}:/data/logs"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge