services:
  proxy:
    image: ${PROXY_IMAGE}
    restart: unless-stopped
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "${VOL_PATH}/proxy/data:/data"
      - "${VOL_PATH}/proxy/letsencrypt:/etc/letsencrypt"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge