version: '3.8'

services:
  proxy:
    image: ${PROXY_IMAGE:-jc21/nginx-proxy-manager:latest}
    restart: unless-stopped
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "./data/proxy:/data"
      - "./data/proxy-letsencrypt:/etc/letsencrypt"
    networks:
      - proxy
