services:
  monica:
    image: ${MONICA_IMAGE:-latest}
    restart: unless-stopped
    environment:
      - DB_HOST=${MONICA_DB_HOST:-monica-db}
      - DB_USERNAME=${MONICA_DB_USERNAME:-monica}
      - DB_PASSWORD=${MONICA_DB_PASSWORD:-changeme}
      - APP_ENV=${MONICA_APP_ENV:-production}
    volumes:
      - ${VOL_PATH}/monica:/var/www/html/storage
