services:
  lubelogger:
    image: ${LUBELOGGER_IMAGE:-ghcr.io/hargata/lubelogger:latest}
    restart: ${LUBELOGGER_RESTART:-unless-stopped}
    volumes:
      - ${VOL_PATH:-/data}/lubelogger/data:/App/data
      - ${VOL_PATH:-/data}/lubelogger/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "${LUBELOGGER_PORT:-8080}:8080"
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
