services:
  jellyseerr:
    container_name: jellyseerr
    image: ${JELLYSEERR_IMAGE}
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${VOL_PATH}:/config