version: "3.4"

services:
  semaphore:
    image: ${SEMAPHORE_IMAGE:-semaphoreui/semaphore:latest}
    environment:
      SEMAPHORE_DB_DIALECT: ${SEMAPHORE_DB_DIALECT:-bolt}
      SEMAPHORE_PLAYBOOK_PATH: ${SEMAPHORE_PLAYBOOK_PATH:-/tmp/semaphore/}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD:-changeadmin1234}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME:-admin}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION:-dfTa9mOCsaoM1zZ+YBE+eGSZnEB0sXvHePhatj9ohuk=}
      SEMAPHORE_LDAP_ACTIVATED: ${SEMAPHORE_LDAP_ACTIVATED:-no}
    volumes:
      - ${CONFIG_VOL:-./config}/config.json:/home/semaphore/config.json
      #- ./config/ssh/:/home/semaphore/.ssh
    ports:
      - ${SEMAPHORE_PORT:-3000}:3000
