services:

  semaphore:
    image: ${SEMAPHORE_IMAGE:-semaphoreui/semaphore:latest}
    environment:
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER:-semaphore}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS:-semaphorepass}
      SEMAPHORE_DB_HOST: semaphore-mariadb
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: ${SEMAPHORE_PLAYBOOK_PATH:-/tmp/semaphore/}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD:-changeadmin1234}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME:-admin}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION:-dfTa9mOCsaoM1zZ+YBE+eGSZnEB0sXvHePhatj9ohuk=}
      SEMAPHORE_LDAP_ACTIVATED: 'no'
    volumes:
      - ${VOL_PATH}/semaphore/app:${SEMAPHORE_PLAYBOOK_PATH:-/tmp/semaphore/}
      - ${VOL_CONFIG_PATH:-./config}/ssh/:/home/semaphore/.ssh/
      - ${VOL_CONFIG_PATH:-./config}/etchosts:/etc/hosts
